(function($){"use strict";var PANEL=window.PANEL||{},bulkArray={};PANEL.toggle=function(){var $elopen=$('.panel_open'),$elclose=$('.panel_close'),$target=$('.theme_panel'),transitionEvent=whichTransitionEvent();var onEndTransitionFn=function(ev){if(!$target.hasClass('opened'))$('.theme_panel_container',$target).hide();};if(transitionEvent){$target[0].addEventListener(transitionEvent,onEndTransitionFn);}else{onEndTransitionFn();}
$elopen.on("click",function(e){e.preventDefault();$target.toggleClass("opened");if($target.hasClass('opened'))$('.theme_panel_container',$target).show();return false;});};PANEL.buttons=function(){var $save=$('.panel_footer #saveCookies'),$saveOption=$('.panel_body .btn-save-option'),$boxedBack=$('.panel_body .boxed-back'),$reset=$('.panel_body #resetCookies');function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function eraseCookie(name){createCookie(name,"",-1);}
$saveOption.on("click",function(e){var getData=$(e.currentTarget).data();if(getData.id==='_uncode_boxed'){createCookie('_uncode_just_boxed','on');}
createCookie(getData.id,getData.value);window.location.href=window.location.href.match(/^[^\#\?]+/)[0];});$boxedBack.on("click",function(e){var getData=$(e.currentTarget).data(),getSrc=$(e.currentTarget).attr('img-src'),backArray=String(getData.back).split(",");backArray[backArray.length-1]=getData.id;$('.box-wrapper').css({'background-image':'url('+getSrc+')','background-size':'cover','background-attachment':'fixed'});$('.panel_section .boxed-back.btn-disable-hover').removeClass('btn-disable-hover');$(e.currentTarget).addClass('btn-disable-hover');createCookie('_uncode_body_background',backArray.join(','));});var $boxedWidth=$('.theme_panel #boxed-range'),$style=$("<style type='text/css'>").appendTo('head');function changeWidth(value){var css="\
                .limit-width {\
                    max-width:   "+value+"px;\
                }";$style.html(css);window.dispatchEvent(UNCODE.boxEvent);if(document.createEvent){window.dispatchEvent(new Event('resize'));}else{document.body.fireEvent('onresize');}}
$boxedWidth.on("change",function(e){changeWidth($(this).attr('value'));createCookie('_uncode_main_width',$(this).attr('value')+',px');});$reset.on("click",function(e){var cookies=document.cookie.split(";");for(var i=0;i<cookies.length;i++){var getTheCookie=cookies[i].split("=")[0];if(getTheCookie.indexOf("_uncode")>-1)eraseCookie(getTheCookie);}
var href=document.location.href;var new_url;var index=href.indexOf('?');if(index>0){new_url=href.substring(0,index);}
window.location.href=new_url;});};PANEL.select=function(){var $el=$('.theme_panel select');$el.each(function(){$(this).on("change",function(e){bulkArray[$(this).attr('data-id')]='='+ $(this).attr('value')+"; expires=0; path=/";});});};PANEL.input=function(){var $el=$('.theme_panel input[type="text"], .theme_panel input[type="number"]');$el.each(function(){$(this).on("input",function(e){bulkArray[$(this).attr('data-id')]='='+ $(this).val()+"; expires=0; path=/";});});};PANEL.switch=function(){var $el=$('.theme_panel input[type=checkbox]');$el.each(function(){$(this).on("change",function(e){if($(this).is(':checked')==true){bulkArray[$(this).attr('data-id')]='=on; expires=0; path=/';}else{bulkArray[$(this).attr('data-id')]='=off; expires=0; path=/';}
if($(this).attr('data-id')=='_uncode_boxed'){if($('.boxed-box').css('display')=='none'){$('.boxed-box').show();}else $('.boxed-box').hide();}});});};PANEL.showChat=function(){var $container,$iframe;$('#menu-item-65136 > a, .panel_chat > a').on('click',function(e){e.preventDefault();$container=$('#intercom-container');$iframe=$('iframe',$container);$iframe.contents().find('.intercom-launcher-open-icon')[0].setAttribute('style','display:none!important');if($.isFunction(Intercom)){Intercom('show');$container.addClass('frame-loaded').addClass('open-panel-chat');$iframe.contents().find('.intercom-launcher-close-icon, .intercom-launcher-discovery').on('click',function(){$container.removeClass('open-panel-chat');});}});};PANEL.color=function(){var options={color:false,mode:'hsl',controls:{horiz:'s',vert:'l',strip:'h'},hide:true,border:true,target:false,width:200,palettes:true,change:function(event,ui){bulkArray[$(this).attr('data-id')]='='+ $(this).val()+'; expires=0; path=/';}}
$('.color-picker').iris(options);};PANEL.init=function(){PANEL.toggle();PANEL.buttons();PANEL.showChat();}
$(function(){PANEL.init();});})(jQuery);